return {
PlaceObj('ModItemBuildingTemplate', {
	'Group', "Life-Support",
	'Id', "FlourMill",
	'template_class', "MachinePartsFactory",
	'resource_produced1', "Food",
	'max_storage1', 100000,
	'production_per_day1', 75000,
	'pin_rollover_hint', T(536055100794, --[[ModItemBuildingTemplate FlourMill pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Select"),
	'pin_rollover_hint_xbox', T(232947681374, --[[ModItemBuildingTemplate FlourMill pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> View"),
	'construction_cost_Concrete', 12000,
	'construction_cost_Metals', 5000,
	'construction_cost_MachineParts', 2000,
	'build_points', 5000,
	'dome_required', true,
	'upgrade1_id', "MachinePartsFactory_FactoryAI",
	'upgrade1_display_name', T(435479078202, --[[ModItemBuildingTemplate FlourMill upgrade1_display_name]] "Factory AI"),
	'upgrade1_description', T(141474585228, --[[ModItemBuildingTemplate FlourMill upgrade1_description]] "+<upgrade1_mul_value_1>% Production."),
	'upgrade1_icon', "UI/Icons/Upgrades/factory_ai_01.tga",
	'upgrade1_upgrade_cost_Electronics', 5000,
	'upgrade1_upgrade_cost_MachineParts', 2000,
	'upgrade1_mod_prop_id_1', "production_per_day1",
	'upgrade1_mul_value_1', 20,
	'upgrade2_id', "MachinePartsFactory_Automation",
	'upgrade2_display_name', T(523692374191, --[[ModItemBuildingTemplate FlourMill upgrade2_display_name]] "Automation"),
	'upgrade2_description', T(132277227218, --[[ModItemBuildingTemplate FlourMill upgrade2_description]] "Decreases Workplaces by <abs(upgrade2_add_value_1)>."),
	'upgrade2_icon', "UI/Icons/Upgrades/automation_01.tga",
	'upgrade2_upgrade_cost_Metals', 2000,
	'upgrade2_upgrade_cost_Electronics', 3000,
	'upgrade2_upgrade_cost_MachineParts', 2000,
	'upgrade2_mod_prop_id_1', "max_workers",
	'upgrade2_add_value_1', -1,
	'upgrade3_id', "MachinePartsFactory_Amplify",
	'upgrade3_display_name', T(710517375398, --[[ModItemBuildingTemplate FlourMill upgrade3_display_name]] "Amplify"),
	'upgrade3_description', T(695036552753, --[[ModItemBuildingTemplate FlourMill upgrade3_description]] "+<upgrade3_mul_value_1>% Production; + Consumption."),
	'upgrade3_icon', "UI/Icons/Upgrades/amplify_01.tga",
	'upgrade3_upgrade_cost_Concrete', 2000,
	'upgrade3_upgrade_cost_Metals', 1000,
	'upgrade3_upgrade_cost_Electronics', 1000,
	'upgrade3_upgrade_cost_MachineParts', 1000,
	'upgrade3_mod_prop_id_1', "production_per_day1",
	'upgrade3_mul_value_1', 25,
	'upgrade3_mod_prop_id_2', "electricity_consumption",
	'upgrade3_mul_value_2', 50,
	'maintenance_resource_type', "Concrete",
	'maintenance_resource_amount', 500,
	'consumption_resource_type', "Seeds",
	'consumption_max_storage', 10000,
	'consumption_amount', 800,
	'display_name', T(901930220682, --[[ModItemBuildingTemplate FlourMill display_name]] "Flour Mill"),
	'display_name_pl', T(199473000783, --[[ModItemBuildingTemplate FlourMill display_name_pl]] "Flour Mills"),
	'description', T(678638449288, --[[ModItemBuildingTemplate FlourMill description]] "Produces Flour (Food) from Seeds."),
	'build_category', "Life-Support",
	'display_icon', "UI/Icons/Buildings/machine_parts_factory.tga",
	'build_pos', 13,
	'entity', "MachinePartsFactory",
	'encyclopedia_id', "FlourMill",
	'encyclopedia_text', T(403043939624, --[[ModItemBuildingTemplate FlourMill encyclopedia_text]] "Turns surplus seeds into flour."),
	'encyclopedia_image', "UI/Encyclopedia/MachinePartsFactory.tga",
	'label1', "InsideBuildings",
	'label2', "FactoryBuildings",
	'palette_color1', "inside_accent_factory",
	'palette_color2', "cables_base",
	'palette_color3', "inside_metal",
	'demolish_sinking', range(15, 25),
	'demolish_debris', 85,
	'electricity_consumption', 5000,
	'enabled_shift_2', false,
	'enabled_shift_3', false,
	'max_workers', 2,
}),
PlaceObj('ModItemCode', {
	'FileName', "Code/Script.lua",
}),
}
